name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Run PHPStan with ReviewDog
      uses: GeneaLabs/action-reviewdog-phpstan@1.1.2
      with:
        # GITHUB_TOKEN
        github_token: ${{ github.token }}
        # Report level for reviewdog [info,warning,error].
        level: warning
        # Report level for phpstan.
        phpstan_level: 4
        # Reporter of reviewdog command [github-pr-check,github-pr-review].
        reporter: github-pr-check
        # Directory to run checks against.
        target_directory: src
        # Fail on error.
        fail_on_error: false
        # Catch-all for any command-line arguments you would like to add.
        args: #um
      

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
